// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AntDesign:appleOutlined': typeof import('~icons/ant-design/apple-outlined')['default']
    'AntDesign:underlineOutlined': typeof import('~icons/ant-design/underline-outlined')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    Footer: typeof import('D:/CODE/GITHUB/vitesse-route-demo/src/components/Footer.vue')['default']
    'Mdi:abTesting': typeof import('~icons/mdi/ab-testing')['default']
    README: typeof import('D:/CODE/GITHUB/vitesse-route-demo/src/components/README.md')['default']
  }
}

export { }
